import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';

import 'theme/theme.dart';
import 'providers/auth_provider.dart';
import 'providers/habit_provider.dart';
import 'providers/settings_provider.dart';
import 'services/auth_service.dart';
import 'services/notification_service.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Try initializing Firebase, but catch errors to allow running in Mock mode
  try {
    // If the firebase_options file was generated by flutterfire, initialize it.
    // Otherwise, this will throw an exception which we handle gracefully.
    await Firebase.initializeApp();
    AuthService.setUseFirebase(true);
    debugPrint(
      'Firebase successfully initialized. App is running in Firebase Auth mode.',
    );
  } catch (e) {
    AuthService.setUseFirebase(false);
    debugPrint('Firebase is not configured or failed to initialize: $e');
    debugPrint(
      'Fallback: The application is running in persistent Mock Auth mode.',
    );
  }

  // Initialize local notification configurations
  final NotificationService notificationService = NotificationService();
  await notificationService.init();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => SettingsProvider()),
        ChangeNotifierProvider(
          create: (_) => AuthProvider()..checkAuthSession(),
        ),
        ChangeNotifierProvider(create: (_) => HabitProvider()),
      ],
      child: const HabittApp(),
    ),
  );
}

class HabittApp extends StatelessWidget {
  const HabittApp({super.key});

  @override
  Widget build(BuildContext context) {
    final settingsProvider = Provider.of<SettingsProvider>(context);
    final authProvider = Provider.of<AuthProvider>(context);

    return MaterialApp(
      title: 'Habitt',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: settingsProvider.isDarkTheme
          ? ThemeMode.dark
          : ThemeMode.light,
      home: authProvider.isAuthenticated
          ? const HomeScreen()
          : const LoginScreen(),
    );
  }
}
